### ISSUE TITLE
Possible to add a footer to explain the rings?

### ISSUE THREAD

**Issue by ghost** [camunda/technology-radars#20]
The [original radar](https://www.thoughtworks.com/radar) has an [FAQ](https://www.thoughtworks.com/radar/faq) that explains the rings. Do you know of an easy way to add maybe a footer to our https://shared.radar.camunda.cloud/ to explain our rings? Just an idea. Not strictly necessary.

CC @quentinleroy

**Comment by cmur2** [comment]
Looking at the [help to Build Your Own Radar](https://www.thoughtworks.com/radar/how-to-byor) (which is the feature that we use, via https://radar.thoughtworks.com) I don't see a way to parameterize anything besides the URL to the data.

To see our "implementation": https://github.com/camunda/infra-core/blob/stage/camunda-pub/kustomize/prod/radar/radar.camunda.cloud/ingress.yml (we basically redirect the traffic and derive the URL to the data from the domain name)

**Comment by ghost** [comment]
Thanks for checking, @cmur2!
